name: Node.js CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  # required for all workflows
  security-events: write

  # only required for workflows in private repositories
  actions: read
  contents: read

  checks: write
  
  # For publishing provenance to npm  
  id-token: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install and configure
        uses: actions/setup-node@v6
        with:
          node-version: '22.21.1'

      - name: Install tools
        run: |
          npm i -g npm@10.9.2
          npm i -g npm-check

      - name: Check tool versions
        run: |
          node --version
          npm --version

      - name: Clean install dependencies
        run: npm ci

      - name: License header check
        run: npm run license-check check

      - name: Run ESLint
        run: npm run eslint-junit || true # Always succeed, even with linting errors

      - name: Report ESLint results
        uses: dorny/test-reporter@v3
        if: success() || failure()
        with:
          name: ESLint Results
          path: "eslint-junit.xml"
          reporter: java-junit
          fail-on-error: false

      - name: Run ESLint
        run: npm run eslint-sarif || true # Always succeed, even with linting errors

      - name: Upload EsLint scan results to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'eslint_report.sarif'
            
            
      #- name: Archive lint reports
      #  if: ${{ success() }} || ${{ failure() }}
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: MegaLinter reports
      #    path: |
      #      megalinter-reports
      #      mega-linter.log
                      
      - name: Build
        run: npm run build
        
        # Don't link any more - we'll do that from the repo that uses this
        
        
        # publish

      - name: Setup Publish
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/setup-node@v6
        with:
          node-version: '22.21.1'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds

      - name: Publish
        if: success() && github.ref == 'refs/heads/main'
        run: npm publish --verbose --provenance --access public


      - name: Send a stream message
        if: (success() || failure()) && github.actor != 'dependabot[bot]'
        uses: zulip/github-actions-zulip/send-message@v2
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: "githubactionsbot-bot@maurodatamapper.zulipchat.com"
          organization-url: "https://maurodatamapper.zulipchat.com"
          to: "build/github-actions"
          type: "stream"
          topic: "${{github.repository}}"
          content: "${{ job.status == 'success' && ':check_mark:' || ':cross_mark:' }} ${{github.repository}} : **${{github.ref}}**\nGitHub Actions build result: **${{ job.status }}**\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"    